name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/setup-node@master

    - name: npm install
      run: npm install
      working-directory: /home/runner/work/stopwatch/stopwatch

    - name: Compile
      run: npm run build:prod
      working-directory: /home/runner/work/stopwatch/stopwatch